# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Luigi Luz
tagline:          'Mostly about technology'
description:      'A blog about technology related topics (mostly about embedded systems and artificial intelligence applications).'
url:              /luigiluz.github.io/
baseurl:          /

author:
  name:           'Luigi Luz'
  url:            https://www.linkedin.com/in/luigi-luz/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/luigiluz

collections:
  projects:
      output: true
      permalink: /:collection/:title
